### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by X-ZhiMing** [MANDO-Project/ge-sc#2]
python -m experiments.graph_classification --epochs 50 --repeat 20

This command cannot be run

**Comment by minhnn-tiny** [comment]
Thanks for your comment!
I fixed the model structure instead of passing as command-line arguments to be consistent with the command.
Please refer to https://github.com/MANDO-Project/ge-sc/commit/2a54f1916caf0a4100de6d6590b16923479f1879.
